name: Lint & Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # 👇  add this block so python can import from src/
    env:
      PYTHONPATH: src

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -U ruff pytest pytest-cov
      - run: ruff check .
      - run: pytest -q --cov=src
